// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6x7DtprqTh2go34Rbxhsjg_LYfMujqwk',
    appId: '1:1006357572367:web:2f54d663a39d9478adec7a',
    messagingSenderId: '1006357572367',
    projectId: 'myapp-nandakishor-flutter-proj',
    authDomain: 'myapp-nandakishor-flutter-proj.firebaseapp.com',
    storageBucket: 'myapp-nandakishor-flutter-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTdMoSUxGqCrFLWkesTTSXebfk20K450',
    appId: '1:1006357572367:android:a7a73cf362756aebadec7a',
    messagingSenderId: '1006357572367',
    projectId: 'myapp-nandakishor-flutter-proj',
    storageBucket: 'myapp-nandakishor-flutter-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk05wx_g4sjFOf369nsW6zh2pgP7v94lo',
    appId: '1:1006357572367:ios:a0b437420871a389adec7a',
    messagingSenderId: '1006357572367',
    projectId: 'myapp-nandakishor-flutter-proj',
    storageBucket: 'myapp-nandakishor-flutter-proj.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk05wx_g4sjFOf369nsW6zh2pgP7v94lo',
    appId: '1:1006357572367:ios:b7962296591a045fadec7a',
    messagingSenderId: '1006357572367',
    projectId: 'myapp-nandakishor-flutter-proj',
    storageBucket: 'myapp-nandakishor-flutter-proj.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
